# Generated by Django 4.0.5 on 2022-07-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0004_delete_gato'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
